services:
  - type: web
    name: telegram-movie-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python smart_search_bot.py"
    autoDeploy: true
